### ISSUE TITLE
Can I test other meshes without training?

### ISSUE THREAD

**Issue by Ctensorflow** [threedle/iSeg#3]
Hello, Thanks for your job! 
I wonder if I could test my own meshes without training since preparing the decoder datasets cost too much time! 

Thanks in advance!

**Comment by itailang** [comment]
Hello @Ctensorflow,

Thanks for your interest in our work. iSeg is trained per shape and is unlikely to work for a shape it was not trained on.

What you can do to reduce the data preparation time is to reduce the number of training vertices, i.e., instead of using 3% of the vertices, set the number yourself. However, it may reduce the quality of the model.

Please let me know if you have any further questions. Thanks!
